apiVersion: v1
kind: Secret
metadata:
  name: captcha-app-secret
  namespace: agami
type: Opaque
stringData:
  DATABASE_URL: "<REPLACE_ME>"
  API_KEY_HMAC_PEPPER: "<REPLACE_ME>"
  CAPTCHA_TOKEN_SECRET: "<REPLACE_ME>"
